### ISSUE TITLE
First contributor repository in the zimfw organization

### ISSUE THREAD

**Issue by ericbn** [zimfw/minimal#1]
@PatTheMav, what do you think of moving your fork of minimal, which you have carefully crafted to use Zim's features, to our organization?

**Comment by PatTheMav** [comment]
@ericbn More than happy to - will try to have this done by end of next week.

**Comment by PatTheMav** [comment]
@ericbn So I've tried to push an initial commit, which failed (probably due to permissions). I had to do some zimfw-exclusive changes to the theme that I don't want to push to my more "open" branch to break compatibility with non-zimfw users (as people have forked my fork already as well).

I guess you'd prefer pull requests (but even then Github only shows me how to do the initial commit - which fails).

**Comment by ericbn** [comment]
@PatTheMav, you're the Admin of the repo. You should be even able to open https://github.com/zimfw/minimal/settings/collaboration. It's weird that you won't be able to do anything with it.

It's up to you if you prefer to maintain two versions of the theme, as you mentioned, or just your repo. I thought it was only for Zim users. No worries.

**Comment by PatTheMav** [comment]
@ericbn Figured out what was wrong - initial commit done.

**Comment by ericbn** [comment]
@PatTheMav, I've been comparing some changes you did to the original code, and most of them you could even suggest as changes to the original repo. Like using `f()` instead of `function f` (there's even a `function _mnml_bind_widgets()` where subnixr is mixing both ways), like using the prompt_percent sequences for colors and for status, err and jobs.

If subnixr is even willing to accept using `${variables_around_curly_braces}`, it would also bring it closer to [Zim's Code Style Guide](https://github.com/zimfw/zimfw/wiki/Code-Style-Guide). Using `[[ ]]` instead of `[ ]` would also be a nice change in both sides.

Let me also open a PR here with changes you can do to bring your code closed to original one (changes I don't think are necessary, in other words).

EDIT: PR is #2

**Comment by PatTheMav** [comment]
@ericbn I think this indeed makes sense for this specific bundled version of minimal.

My own version starts to diverge a bit more, adding more functionality and _possibly_ making it less minimal than subnixr might like, which was also the reason why I chose to keep it separate.

That said, the original had no `git-info` functionality and if we could make this optional (by incorporating his original `git` functionality as a fallback) we might even be able to just clone the "original" again.

EDIT: I've added a check for `git-info` in my other fork which restores the original functionality if that module is not available. Will adapt it later tonight.

**Comment by ericbn** [comment]
The idea of using the original implementation if `git-info` is not available is a very good one.

I would keep it simple and (1) try to submit as much changes as possible upstream, since you'll be contributing to a larger audience and also getting better feedback, and (2) try not to maintain two versions of it (in your user account, and here). Just my two cents...  :- )

**Comment by PatTheMav** [comment]
Yeah so that's the "roadmap", introduce changes to the original if possible to bring parity, then introduce new features either there or locally.

**Comment by PatTheMav** [comment]
@ericbn I've revisited both themes today and came to the conclusion that it'd probably be better to "deprecate" this repo and let users add the original minimal version if they so choose. My thinking went:

* Introducing `git-info` functionality/code is of zero use to the theme itself (as it's a specific `zim` feature)
* Otherwise most changes were made to be more compliant to `zim`'s code style guidelines or to use more `zsh`-like syntax

The latter also makes functionally no real difference to users (I haven't checked the performance impact, if there is any) so I'd guess users might be better served to use either the original as-is and if they want a more customised version use my fork.

Alternatively we could rename this repo "zimfw-minimal" but then have to accept that it'll be its own thing, diverged from the original ~2 years ago.

**Comment by ericbn** [comment]
@PatTheMav, makes sense! I've created an [announcement](https://github.com/zimfw/zimfw/discussions/426) discussion, and we could announce the depreciation of this repo there. Should we delete the repo after that, or archive it?

**Comment by PatTheMav** [comment]
I'd archive it, to avoid breaking update runs on configs that use it. An announcement of deprecation, explaining that the repo will exist, but we won't maintain it (and point to the original and my fork as alternatives) should suffice.

I haven't deprecated my fork either, just not really added any features.

**Comment by ericbn** [comment]
@PatTheMav, you're the admin of this repo. Feel free to add the deprecation notice and archive it when you consider appropriate.
